[[cors]]
allowed_origins = "*"
allowed_methods = ["GET", "POST"]
allowed_headers = "*"

[[headers]]
for = ["**/*.woff2", "**/*.woff", "**/*.svg", "**/*.ttf", "**/*.otf", "**/*.eot", "**/*.js", "**/*.css"]
compress = "gzip"
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[headers]]
for = ["**/*.png", "**/*.jpg", "**/*.jpeg", "**/*.gif", "**/*.webp"]
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[redirects]]
from = "/projets/2024-serie-3/"
to = "/series/2024-quentin-dumontet/"

[[redirects]]
from = "/projets/"
to = "/series/"

[[redirects]]
from = "/series/2024-damian-tokatlian/"
to = "/series/2024-damien-tokatlian/"

[[redirects]]
from = "/series/2024-serie-2/"
to = "/series/2024-celia-nageuse/"

[[redirects]]
from = "/series/2024-celia/"
to = "/series/2024-celia-nageuse/"

[[redirects]]
from = "/projets/2024-serie-5/"
to = "/series/2024-pianiste/"

[[redirects]]
from = "/series/2024-serie-3/"
to = "/series/2024-quentin-dumontet/"

[[redirects]]
from = "/series/2024-serie-5/"
to = "/series/2024-pianiste/"

[[redirects]]
from = "/projets/2024-serie-4/"
to = "/series/2024-matthieu-gerbort/"

[[redirects]]
from = "/series/2024-serie-4/"
to = "/series/2024-matthieu-gerbort/"

[[redirects]]
from = "/projets/2024-serie-1/"
to = "/series/2024-damien-tokatlian/"

[[redirects]]
from = "/series/2024-audrey-dore/"
to = "/series/2024-celia-nageuse/"

[[redirects]]
from = "/projets/2024-serie-2/"
to = "/series/2024-celia-nageuse/"

[[redirects]]
from = "/series/2024-serie-1/"
to = "/series/2024-damien-tokatlian/"

[[redirects]]
from = "/series/2024-musician/"
to = "/series/2024-pianiste/"

